### ISSUE TITLE
Tons of memory leaks

### ISSUE THREAD

**Issue by qwertymodo** [snes9xgit/snes9x#248]
Compiling the Windows port with CHECK_MEMORY_LEAKS defined results in a huge number of leaks reported.  By far, the most common leak is 8 bytes in size, with the last 4 bytes always 0x00.  There isn't much in the way of recognizable data, but I do see a few strings which appear to be config file comments, such as "ordering within", "if true, prevent", "true to allow en", "IgnorePatchCheck", etc.  It would probably be a good idea to work on cleaning those up.

**Comment by bonimy** [comment]
I had this exact problem when I tried building SMB Utility. What I noticed were memory leaks occuring whenever a `printf()` [function](http://www.cplusplus.com/reference/cstdio/printf/) was used to print a byte. 
Before the C++11 standard, passing a byte to format would guarantee a memory leak because the function would read a full integer. So best way to tackle this issue -my guess anyway- is to change the formatting of these printf functions to parse the pointers as bytes, not integers.

**Comment by Felipefpl** [comment]
Hi, i'd like to give you a hint: this tool http://deleaker.com/index.html helps to find stuff that usually isnt found by other detectors, it's also used by this mod https://github.com/GrognardsFromHell/TemplePlus i hope it can be useful for you to fix the things you find.

**Comment by OV2** [comment]
I've fixed some at exit leaks, currently only one remains (rom_filename points to a strdup that is never released).

Most of the messages come from the fact that _CrtDumpMemoryLeaks is called at the end of WinMain, which is before destructors of global objects have run. I've tried to work around that in another commit.

**Comment by qwertymodo** [comment]
That definitely fixed a bunch of them.  I still see a handful of leaks which might be MSU-1 related.  One that I'm seeing repeatedly with the same size and content is

```
{64884} normal block at 0x1454CF48, 180 bytes long.
 Data: <  t   t P t   t > B0 06 74 00 20 07 74 00 50 07 74 00 80 07 74 00
```

Then there's a block of size 16,384 and one of size 32,768, and a handful of smaller ones.  Actually, now that I am trying it again, that 180 byte repeated one might only be showing up when loading a .msu1 (zip) file.  I don't get any leaks for non-MSU games now, so that's good.

**Comment by OV2** [comment]
I've pushed another commit that should fix msu1 leaks. I've tried uncompressed and .msu1 and both no longer give me any leaks.

**Comment by qwertymodo** [comment]
Looks good here.
