### ISSUE TITLE
[libretro] Build failure on linux

### ISSUE THREAD

**Issue by orbea** [snes9xgit/snes9x#366]
OS: `Slackware64-14.2`
Compiler: `gcc-5.5.0`

When building the libretro port with this repo on Slackware stable (14.2) it will fail to build.
```
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../apu/apu.o ../apu/apu.cpp
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../apu/bapu/dsp/sdsp.o ../apu/bapu/dsp/sdsp.cpp
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../apu/bapu/dsp/SPC_DSP.o ../apu/bapu/dsp/SPC_DSP.cpp
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../apu/bapu/smp/smp.o ../apu/bapu/smp/smp.cpp
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../apu/bapu/smp/smp_state.o ../apu/bapu/smp/smp_state.cpp
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -DGIT_VERSION=\"" c6db74c"\" -DLAGFIX -O2 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC -DRIGHTSHIFT_IS_SAR -D__LIBRETRO__ -DHAVE_STRINGS_H -fno-rtti -pedantic  -fno-exceptions -c -o../bsx.o ../bsx.cpp
In file included from ../snes9x.h:200:0,
                 from ../apu/bapu/snes/snes.hpp:4,
                 from ../apu/bapu/dsp/sdsp.cpp:1:
../port.h:283:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long   int64;
              ^
../port.h:284:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef unsigned long long uint64;
                       ^
In file included from ../snes9x.h:200:0,
                 from ../apu/apu.cpp:193:
../port.h:283:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long   int64;
              ^
../port.h:284:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef unsigned long long uint64;
                       ^
In file included from ../apu/bapu/dsp/SPC_DSP.cpp:5:0:
../apu/bapu/dsp/SPC_DSP.cpp: In member function 'int SPC_State_Copier::copy_int(int, int)':
../apu/bapu/dsp/blargg_endian.h:129:68: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   #define SET_LE16( addr, data )  (void) (*(BOOST::uint16_t*) (addr) = (data))
                                                                    ^
../apu/bapu/dsp/SPC_DSP.cpp:894:2: note: in expansion of macro 'SET_LE16'
  SET_LE16( s, state );
  ^
../apu/bapu/dsp/blargg_endian.h:127:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   #define GET_LE16( addr )        (*(BOOST::uint16_t*) (addr))
                                                             ^
../apu/bapu/dsp/SPC_DSP.cpp:896:9: note: in expansion of macro 'GET_LE16'
  return GET_LE16( s );
         ^
In file included from ../snes9x.h:200:0,
                 from ../bsx.cpp:197:
../port.h:283:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long   int64;
              ^
../port.h:284:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef unsigned long long uint64;
                       ^
In file included from ../snes9x.h:200:0,
                 from ../apu/bapu/snes/snes.hpp:4,
                 from ../apu/bapu/smp/smp.cpp:10:
../port.h:283:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long   int64;
              ^
../port.h:284:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef unsigned long long uint64;
                       ^
In file included from ../snes9x.h:200:0,
                 from ../apu/bapu/snes/snes.hpp:4,
                 from ../apu/bapu/smp/smp_state.cpp:1:
../port.h:283:14: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef long long   int64;
              ^
../port.h:284:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
 typedef unsigned long long uint64;
                       ^
In file included from ../apu/bapu/dsp/SPC_DSP.cpp:5:0,
                 from ../apu/bapu/dsp/sdsp.cpp:8:
../apu/bapu/dsp/SPC_DSP.cpp: In member function 'int SNES::SPC_State_Copier::copy_int(int, int)':
../apu/bapu/dsp/blargg_endian.h:129:68: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   #define SET_LE16( addr, data )  (void) (*(BOOST::uint16_t*) (addr) = (data))
                                                                    ^
../apu/bapu/dsp/SPC_DSP.cpp:894:2: note: in expansion of macro 'SET_LE16'
  SET_LE16( s, state );
  ^
../apu/bapu/dsp/blargg_endian.h:127:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   #define GET_LE16( addr )        (*(BOOST::uint16_t*) (addr))
                                                             ^
../apu/bapu/dsp/SPC_DSP.cpp:896:9: note: in expansion of macro 'GET_LE16'
  return GET_LE16( s );
         ^
../apu/apu.cpp: In function 'void S9xAPULoadBlarggState(uint8*)':
../apu/apu.cpp:795:5: error: 'uint8_t' was not declared in this scope
     uint8_t regs_in [0x10];
     ^
../apu/apu.cpp:796:13: error: expected ';' before 'regs'
     uint8_t regs [0x10];
             ^
../apu/apu.cpp:797:5: error: 'uint16_t' was not declared in this scope
     uint16_t pc, spc_time, dsp_time;
     ^
../apu/apu.cpp:798:13: error: expected ';' before 'a'
     uint8_t a,x,y,psw,sp;
             ^
../apu/apu.cpp:800:17: error: 'regs' was not declared in this scope
     copier.copy(regs,0x10); // REGS
                 ^
../apu/apu.cpp:801:17: error: 'regs_in' was not declared in this scope
     copier.copy(regs_in,0x10); // REGS_IN
                 ^
../apu/apu.cpp:804:5: error: 'pc' was not declared in this scope
     pc = copier.copy_int( 0, sizeof(uint16_t) );
     ^
../apu/apu.cpp:805:5: error: 'a' was not declared in this scope
     a = copier.copy_int( 0, sizeof(uint8_t) );
     ^
../apu/apu.cpp:806:5: error: 'x' was not declared in this scope
     x = copier.copy_int( 0, sizeof(uint8_t) );
     ^
../apu/apu.cpp:807:5: error: 'y' was not declared in this scope
     y = copier.copy_int( 0, sizeof(uint8_t) );
     ^
../apu/apu.cpp:808:5: error: 'psw' was not declared in this scope
     psw = copier.copy_int( 0, sizeof(uint8_t) );
     ^
../apu/apu.cpp:809:5: error: 'sp' was not declared in this scope
     sp = copier.copy_int( 0, sizeof(uint8_t) );
     ^
../apu/apu.cpp:813:5: error: 'spc_time' was not declared in this scope
     spc_time = copier.copy_int( 0, sizeof(uint16_t) );
     ^
../apu/apu.cpp:814:5: error: 'dsp_time' was not declared in this scope
     dsp_time = copier.copy_int( 0, sizeof(uint16_t) );
     ^
../apu/apu.cpp:827:14: error: expected ';' before 'next_time'
     uint16_t next_time[3];
              ^
../apu/apu.cpp:828:13: error: expected ';' before 'divider'
     uint8_t divider[3], counter[3];
             ^
../apu/apu.cpp:831:6: error: 'next_time' was not declared in this scope
      next_time[i] = copier.copy_int( 0, sizeof(uint16_t) );
      ^
../apu/apu.cpp:832:6: error: 'divider' was not declared in this scope
      divider[i] = copier.copy_int( 0, sizeof(uint8_t) );
      ^
../apu/apu.cpp:833:6: error: 'counter' was not declared in this scope
      counter[i] = copier.copy_int( 0, sizeof(uint8_t) );
      ^
../apu/apu.cpp:841:44: error: 'next_time' was not declared in this scope
     SNES::smp.timer0.stage1_ticks = 128 - (next_time[0] - cur_time) / 128;
                                            ^
../apu/apu.cpp:842:37: error: 'divider' was not declared in this scope
     SNES::smp.timer0.stage2_ticks = divider[0];
                                     ^
../apu/apu.cpp:843:37: error: 'counter' was not declared in this scope
     SNES::smp.timer0.stage3_ticks = counter[0];
                                     ^
Makefile:528: recipe for target '../apu/apu.o' failed
make: *** [../apu/apu.o] Error 1
make: *** Waiting for unfinished jobs....
```
However it builds fine for the newer Slackware current (Developmental) and the libretro fork also builds for Slackware stable. Can this also be fixed for this repo too?

**Comment by bearoso** [comment]
Should be fixed now.

**Comment by orbea** [comment]
Thanks, you missed one, but now that I see the fix it was easy to send a PR. :)
https://github.com/snes9xgit/snes9x/pull/367
