### ISSUE TITLE
Super back to the future ii (japan) with fastrom patch is not working

### ISSUE THREAD

**Issue by gabberhead** [snes9xgit/snes9x#809]
Today I tried the game with the fastrom patch from here:

https://www.romhacking.net/hacks/6607/

But the game is not starting in retroarch with the snes9x-current core. The screen goes black and stay this way. Without the fastrom patch the game is starting and running fine. Also with the english translation patch.

Then I tried the patched rom with the standalone version of snes9x on win11 and the the game is starting and running fine. Other older cores from snes9x core in retroarch I didn't tried it right now. But I will try it later.

**Comment by ChocoChopin** [comment]
I just opened an issue with Super Mario All-Stars' Mario 3 hanging using the libretro core, but not with the standalone implementation. I wonder what these quirks could be about.

**Comment by joepogo** [comment]
Can confirm. Just tested this on retroarch snes9x current and then standalone and experiencing the same issues.

I wonder if all fastrom hacks are doing the same thing on retroarch and window standalone builds?

**Comment by gabberhead** [comment]
Some games with fastrom patches are working with the current core on retroarch. For example: aladdin, contra 3 and magical quest 3.
Other game with fastrom patch  i testet is: Adventures of Batman & Robin. With the current core on retroarch, the game is also not working.

**Comment by bearoso** [comment]
I've discovered where the problem is. It's definitely the hacks. In the 1.61 release version, we added a bit that wouldn't map SRAM when it wasn't marked in the header. This broke Mega Man X's copy protection, so we reverted it.

The problem is these hacks are using bank F0-FF where SRAM is mapped. No release game seemingly has anything but SRAM mapped to that range. I can add back the condition to not map that area if sramsize is 0, and hopefully Mega Man X uses an address in the other 70-7D range. I couldn't find any exact details what address it accesses.

**Comment by bearoso** [comment]
I feel I should point out that the hack authors should to fix this on their end. These patches won't work on real hardware, which is kind of the reason for FastROM patches. Emulators can already overclock.

**Comment by bearoso** [comment]
Fixed in a06974940362923c224626c6ecbcf0d96308d75e.

**Comment by gabberhead** [comment]
still not working with the retroarch core. testet with super back to the future ii.

**Comment by bearoso** [comment]
We don't control the RetroArch core.

**Comment by gabberhead** [comment]
ok. i will post it on the libretro github site. thanx anyway :)
